name: csms-ticket-service

services:
  user_postgres:
    image: postgres:16
    container_name: user-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postpost
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  
  user_postgres_test:
    image: postgres:16
    container_name: user-service-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postpost
      POSTGRES_DB: users_test
    ports:
      - "5434:5432"
    volumes:
      - user_pgdata_test:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  user_pgdata: {}
  user_pgdata_test: {}