name: csms-ticket-service

services:
  user_postgres:
    image: postgres:16
    container_name: user-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postpost
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - csms-ticket-service-network
  
  user_postgres_test:
    image: postgres:16
    container_name: user-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postpost
      POSTGRES_DB: users_test
    ports:
      - "5434:5432"
    volumes:
      - user_pgdata_test:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - csms-ticket-service-network
  
  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - csms-ticket-service-network
  
  kafka:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    environment:
      KAFKA_LOG_DIRS: /kafka-data
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://127.0.0.1:9092,INTERNAL://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CREATE_TOPICS: >
        user_events:1:1,
        loyalty_sum:1:1
    depends_on:
      - zookeeper
    networks:
      - csms-ticket-service-network
    volumes:
      - csms-kafka-data:/kafka-data
    ports:
      - '9092:9092'
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - csms-ticket-service-network
    ports:
      - "8003:8080"
    volumes:
      - ./src/Presentation/UserService.Presentation.Kafka/protos:/schemas
    environment:
      kafka.clusters.0.name: kafka
      kafka.clusters.0.bootstrapServers: kafka:9094
      kafka.clusters.0.defaultKeySerde: ProtobufFile
      kafka.clusters.0.defaultValueSerde: ProtobufFile

      kafka.clusters.0.serde.0.name: ProtobufFile
      kafka.clusters.0.serde.0.properties.protobufFilesDir: /schemas/

      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.user_events: users.UserEventKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.payments_sum: loyalty.PaymentsSumKey

      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.user_events: users.UserEventValue
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.payments_sum: loyalty.PaymentsSumValue

networks:
  csms-ticket-service-network:
    driver: bridge

volumes:
  user_pgdata: { }
  user_pgdata_test: { }
  csms-kafka-data: { }