services:
  postgres:
    image: postgres:16
    container_name: csms-ticket-service-users
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postpost
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  
  postgres_test:
    image: postgres:16
    container_name: csms-ticket-service-users-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postpost
      POSTGRES_DB: users_test
    ports:
      - "5434:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: {}
  pgdata_test: {}